[package]
name = "crabnest"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
clap = { version = "3.0.10", features = ["derive"] }
nix = "0.23.1"
once_cell = "1.9.0"
rustyline = "9.1.2"
signal-hook = "0.3.13"
